/**
 * CI test classification for #51.
 *
 * Every `*.test.mjs` file must occur in exactly one group. `ci-groups.test.mjs` enforces that
 * exhaustively, so a new test cannot accidentally inherit an environment nobody chose for it.
 *
 * - core: deterministic planning, schema, state and adapter behavior; Ubuntu / Node 24.
 * - node: module loading and runtime/package integration; Ubuntu / Node 22 and Node 24.
 * - platform: processes, terminals, job objects and shutdown; Ubuntu and Windows.
 * - setup: project identity, state protection, setup, recovery and transactions; Ubuntu and Windows.
 * - consumer: cold project, browser and production-shell journeys; Ubuntu / Node 24 and
 *   Windows / Node 22. The complete shell journey lives here because groups are exclusive.
 */
export const CI_GROUPS = Object.freeze({
  core: Object.freeze([
    "acc-0114-record.test.mjs",
    "action-policy.test.mjs",
    "activate-type.test.mjs",
    "approved-model-pool-state.test.mjs",
    "approved-model-pool.test.mjs",
    "artifact-read-tools.test.mjs",
    "artifact-review-choices.test.mjs",
    "attestations.test.mjs",
    "child-report.test.mjs",
    "ci-groups.test.mjs",
    "consent-record.test.mjs",
    "content-version.test.mjs",
    "controller.test.mjs",
    "create-requirement.test.mjs",
    "credential-broker.test.mjs",
    "cross-cutting-traceability.test.mjs",
    "decision-bundle.test.mjs",
    "decisioning.test.mjs",
    "dependency-freshness.test.mjs",
    "derived-not-stored.test.mjs",
    "diagnostics.test.mjs",
    "effective-assertion.test.mjs",
    "evidence-tools.test.mjs",
    "handoff.test.mjs",
    "ingest-audio.test.mjs",
    "ingest-media.test.mjs",
    "ingest-registry.test.mjs",
    "ingest-service.test.mjs",
    "ingest-store.test.mjs",
    "ingest-watch.test.mjs",
    "ingest-web.test.mjs",
    "initialize-project.test.mjs",
    "kiln-start-entry.test.mjs",
    "launch-checks.test.mjs",
    "link-trace.test.mjs",
    "lint-plan-cli.test.mjs",
    "lint.test.mjs",
    "live-canary.test.mjs",
    "live-model-check.test.mjs",
    "migration-environment-axes.test.mjs",
    "model-selection.test.mjs",
    "negative-controls.test.mjs",
    "orchestrator-root.test.mjs",
    "orchestrator-state.test.mjs",
    "payload-write-outcomes.test.mjs",
    "payload-write.test.mjs",
    "pi-dependency-repair.test.mjs",
    "production-audit.test.mjs",
    "project-status.test.mjs",
    "question.test.mjs",
    "reader-discipline.test.mjs",
    "readme.test.mjs",
    "recovery-request.test.mjs",
    "refusal-matrix.test.mjs",
    "research-enablement.test.mjs",
    "research-permission.test.mjs",
    "research-quote.test.mjs",
    "research.test.mjs",
    "resolve-question.test.mjs",
    "review-write.test.mjs",
    "runtime-records.test.mjs",
    "safe-default-test-command.test.mjs",
    "schema-resolver.test.mjs",
    "skeleton.test.mjs",
    "slice-5c.test.mjs",
    "source-tool.test.mjs",
    "specialist-contract.test.mjs",
    "specialist-role-files.test.mjs",
    "specialist-roles.test.mjs",
    "stage-declared-fields.test.mjs",
    "stage-derivation.test.mjs",
    "stage-docs-in-package.test.mjs",
    "stage-document-write.test.mjs",
    "stage-documents.test.mjs",
    "stage-presentation.test.mjs",
    "stage-scope.test.mjs",
    "stage-skill-operating-instructions.test.mjs",
    "stage-skill-overrides.test.mjs",
    "stage-skills-cli.test.mjs",
    "stage-skills-packaged.test.mjs",
    "stage-skills.test.mjs",
    "task-binding.test.mjs",
    "template.test.mjs",
    "tool-wire-names.test.mjs",
    "url-state.test.mjs",
    "voice-config.test.mjs",
    "voice-dictation.test.mjs",
    "voice-end-to-end.test.mjs",
    "voice-output.test.mjs",
    "voice-speech-text.test.mjs",
    "voice-stt-elevenlabs.test.mjs",
    "voice-tts-elevenlabs.test.mjs",
    "voice.test.mjs",
    "wireframe-projection.test.mjs",
    "workflow-carryover.test.mjs",
  ]),
  node: Object.freeze([
    "change-stream.test.mjs",
    "custom-provider-compat.test.mjs",
    "delegate.test.mjs",
    "delegation-provider-route.test.mjs",
    "environment-model.test.mjs",
    "keyboard-stop.test.mjs",
    "linked-entry-points.test.mjs",
    "mdx-rejection.test.mjs",
    "package-resource-claims.test.mjs",
    "pi-compat-login.test.mjs",
    "pi-compat-oauth-harness.test.mjs",
    "pi-compat-oauth.test.mjs",
    "pi-compat.test.mjs",
    "pi-package-decision-bundle.test.mjs",
    "pi-package-delegate.test.mjs",
    "pi-package-entry.test.mjs",
    "pi-package-load.test.mjs",
    "pi-package-operator-boundary.test.mjs",
    "pi-package-project-status.test.mjs",
    "pi-package-stage-context.test.mjs",
    "pi-package-tool-content.test.mjs",
    "pi-package-tools.test.mjs",
    "pi-package.test.mjs",
    "pi-provider-canary.test.mjs",
    "pi-provider-credentials.test.mjs",
    "pi-session-compaction.test.mjs",
    "pi-session-guard.test.mjs",
    "pi-session-orchestrator.test.mjs",
    "pi-session-tools.test.mjs",
    "pi-settings.test.mjs",
    "pi-trust.test.mjs",
    "provider-fixture.test.mjs",
    "run-identity.test.mjs",
    "server-adapters.test.mjs",
    "shell-boundary.test.mjs",
    "shell-read-boundary.test.mjs",
    "stream-watchdog.test.mjs",
  ]),
  platform: Object.freeze([
    "browser-startup.test.mjs",
    "build-reuse.test.mjs",
    "cleanup-diagnostics.test.mjs",
    "connection-inspection.test.mjs",
    "delegate-real-child.test.mjs",
    "f119-query-diagnostic.test.mjs",
    "first-run-workspace.test.mjs",
    "job-mode-launch.test.mjs",
    "job-object-feasibility.test.mjs",
    "job-shutdown.test.mjs",
    "keyboard-stop-terminal.test.mjs",
    "launcher.test.mjs",
    "pi-pty-confirmation.test.mjs",
    "pi-rpc-structured.test.mjs",
    "pi-session-overflow.test.mjs",
    "pi-session-payload-write.test.mjs",
    "pi-session-stage-write.test.mjs",
    "process-table-priming.test.mjs",
    "process-table-windows.test.mjs",
    "reap.test.mjs",
    "rpc-start.test.mjs",
    "server-port.test.mjs",
    "session-chooser-pty.test.mjs",
    "session-chooser.test.mjs",
    "session-new.test.mjs",
    "session-recovery.test.mjs",
    "setup-pty.test.mjs",
    "shutdown-and-session.test.mjs",
    "shutdown-deadline.test.mjs",
    "shutdown-evidence.test.mjs",
    "shutdown-identity.test.mjs",
    "shutdown-queries.test.mjs",
    "shutdown-root-identity.test.mjs",
    "shutdown-timeline.test.mjs",
    "supervisor.test.mjs",
    "validation-job.test.mjs",
    "voice-capture.test.mjs",
    "voice-playback.test.mjs",
    "windows-job.test.mjs",
  ]),
  setup: Object.freeze([
    "build-cache.test.mjs",
    "content-root.test.mjs",
    "isolation-match.test.mjs",
    "local-state.test.mjs",
    "operator-boundary.test.mjs",
    "project-gitignore.test.mjs",
    "session-guard.test.mjs",
    "setup-command.test.mjs",
    "setup-connections.test.mjs",
    "setup-engine.test.mjs",
    "setup-fix-ignore-pty.test.mjs",
    "setup-input.test.mjs",
    "setup-renderer.test.mjs",
    "setup-transaction.test.mjs",
  ]),
  consumer: Object.freeze([
    "blocker-labels-browser.test.mjs",
    "build-trace.test.mjs",
    "clean-consumer-journey.test.mjs",
    "consumer-delegation.test.mjs",
    "consumer-flow.test.mjs",
    "custom-provider-start.test.mjs",
    "piped-stage1-route.test.mjs",
    "shell-smoke.test.mjs",
    "wireframe-viewer-browser.test.mjs",
  ]),
});

export const CI_ENVIRONMENTS = Object.freeze({
  core: Object.freeze(["ubuntu-24"]),
  node: Object.freeze(["ubuntu-22", "ubuntu-24"]),
  platform: Object.freeze(["ubuntu-24", "windows-24"]),
  setup: Object.freeze(["ubuntu-24", "windows-24"]),
  consumer: Object.freeze(["ubuntu-24", "windows-22"]),
});
