/**
 * The generated stage skills as the repository ships them — TSK-0046, against ACC-0066.
 *
 * ⚠️ **THE COMMITTED FILES, NOT A TEMPORARY COPY.** The CLI's own tests prove the command against copies.
 * This file is about what is actually in `pi-package/skills/` and what CI actually runs: every generated
 * file is byte-equal to the pure generator, and every CI cell runs the check before the suite. It only READS the repository.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { checkStageSkills, GENERATED_HEADER } from "../lib/stage-skills-files.mjs";
import { generateStageSkills } from "../lib/stage-skills.mjs";
import { loadStageDefinitions } from "../lib/stages.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SKILLS = join(ROOT, "pi-package", "skills");
const GENERATED = generateStageSkills(loadStageDefinitions(ROOT));

test("⚠️ ACC-0066 the packaged skills are exactly kiln-planning and the nine the generator produces", () => {
  assert.deepEqual(
    readdirSync(SKILLS).sort(),
    ["kiln-planning", ...GENERATED.map((s) => s.name)].sort(),
    "the skills directory holds something other than the handwritten skill and the generated nine"
  );
  assert.equal(GENERATED.length, 9);

  const signature = JSON.parse(readFileSync(join(ROOT, "pi-package", "signature.json"), "utf8"));
  assert.deepEqual([...signature.skills].sort(), ["kiln-planning", ...GENERATED.map((s) => s.name)].sort(), "the declaration names exactly the ten");

  const manifest = JSON.parse(readFileSync(join(ROOT, "pi-package", "package.json"), "utf8"));
  assert.deepEqual(manifest.pi.skills, ["./skills"], "the manifest still declares the one skills directory");
});

test("⚠️ ACC-0066 every generated skill on disk is the generator's output, byte for byte", () => {
  for (const skill of GENERATED) {
    const bytes = readFileSync(join(ROOT, "pi-package", ...skill.path.split("/")));
    const text = bytes.toString("utf8");

    assert.deepEqual(readdirSync(join(SKILLS, skill.name)), ["SKILL.md"], `${skill.name}: only its SKILL.md`);
    assert.ok(bytes.equals(Buffer.from(skill.content, "utf8")), `${skill.name}: not byte-equal to the generator - regenerate, never edit`);
    assert.equal(text.includes("\r"), false, `${skill.name}: a carriage return`);
    assert.ok(text.endsWith("\n") && !text.endsWith("\n\n"), `${skill.name}: not exactly one trailing newline`);
    assert.ok(text.includes(`\n${GENERATED_HEADER}${skill.stageId}.json. Do not edit this file`), `${skill.name}: the generated header is missing`);
  }

  // And the command agrees, which is what CI runs.
  assert.equal(checkStageSkills(ROOT).status, "clean", JSON.stringify(checkStageSkills(ROOT)));
});

test("⚠️ ACC-0066 the package scripts run the generator and its check", () => {
  const scripts = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")).scripts;
  assert.equal(scripts["skills:generate"], "node bin/generate-stage-skills.mjs");
  assert.equal(scripts["skills:check"], "node bin/generate-stage-skills.mjs --check");
});

test("⚠️ ACC-0066 every CI cell runs the skills check, unconditionally, after npm ci and before the suite", () => {
  const workflow = readFileSync(join(ROOT, ".github", "workflows", "ci.yml"), "utf8").replace(/\r\n/g, "\n");

  // The matrix job's steps, as the ordered list of `- name:` blocks.
  const steps = workflow
    .split(/\n(?=      - name: )/)
    .slice(1)
    .map((block) => ({
      name: (block.match(/^      - name: (.+)$/m) ?? [])[1],
      run: (block.match(/^        run: (.+)$/m) ?? [])[1] ?? null,
      conditional: /^        if: /m.test(block),
    }));

  const at = (run) => steps.findIndex((s) => s.run === run);
  const install = at("npm ci");
  const check = at("npm run skills:check");
  const suite = at("npm test");

  assert.ok(check !== -1, "no CI step runs npm run skills:check");
  assert.ok(install !== -1 && suite !== -1, "the install and suite steps were not found");
  assert.ok(install < check && check < suite, `the check must sit between npm ci and npm test: ${JSON.stringify(steps.map((s) => s.run))}`);
  // ⚠️ EVERY CELL. A step with an `if:` would run on some of the matrix, and line endings and path
  // separators are exactly what differs between the cells it would skip.
  assert.equal(steps[check].conditional, false, "the skills check is conditional, so some cells would not run it");
  assert.match(workflow, /matrix:\n\s+os: \[ubuntu-latest, windows-latest\]\n\s+node: \["22", "24"\]/, "the matrix is no longer both platforms by both Node versions");
});
