/**
 * Render a role definition — TSK-0051 (S11), toward ACC-0072 and ACC-0073.
 *
 * One file per role, at `specialists/<role>.md` in the tool root, beside `stages/`. They belong to
 * Kiln's delegation runtime rather than to Pi's extension, skill and prompt package, so they are not
 * shipped inside `pi-package/` and TSK-0053 resolves them from the tool root.
 *
 * ⚠️ **THE FRONTMATTER STARTS ON LINE ONE (D43).** A generated-by warning above the opening `---` would
 * make the document's frontmatter invalid, and these files are meant to be handed to a child directly.
 * The warning is a YAML comment inside the block instead, where it is both visible and legal.
 *
 * ⚠️ **SCALARS ARE JSON-QUOTED (D44).** A JSON string is a valid YAML scalar and survives a colon, a
 * hash, a quote or a leading dash in ordinary prose. Rendering a description bare would make the file's
 * validity depend on nobody writing "note: this matters" into it.
 *
 * ⚠️ **THE KEY SET IS CLOSED, AND THAT IS WHAT MAKES ACC-0073 ENFORCEABLE.** `name`, `role`,
 * `description`, `tools`, in that order, and nothing else. A `model:` line is then not a field somebody
 * forgot to reject: it is a key outside the set.
 */

import { contractFor } from "./contract.mjs";
import { AUTHORED_FIELDS, ROLE_PROSE } from "./roles.mjs";

export const SPECIALISTS_DIR = "specialists";
export const GENERATED_NOTICE = "# Generated by lib/specialists/render.mjs. Do not edit; run `npm run roles:generate`.";
export const FRONTMATTER_KEYS = Object.freeze(["name", "role", "description", "tools"]);

/** The sections, in the order they are rendered. Fixed, because the reader and the child both rely on it. */
export const SECTIONS = Object.freeze([
  { heading: "Input contract", field: "inputContract" },
  { heading: "Responsibilities", field: "responsibilities" },
  { heading: "Forbidden actions", field: null },
  { heading: "Output schema", field: "outputSchema" },
  { heading: "Exit criteria", field: "exitCriteria" },
  { heading: "Escalation conditions", field: "escalation" },
]);

export const RENDER_REFUSAL = Object.freeze({
  UNKNOWN_ROLE: "unknown-role",
  PROSE_MISSING: "role-prose-missing",
  PROSE_UNEXPECTED_FIELD: "role-prose-unexpected-field",
  PROSE_EMPTY: "role-prose-empty",
  CONTRACT_UNSOUND: "role-contract-unsound",
  NO_TOOLS: "role-declares-no-tools",
});

export class RoleRenderRefusal extends Error {
  constructor(code, message) {
    super(message);
    this.name = "RoleRenderRefusal";
    this.code = code;
  }
}

/** The skill-style name a child is launched under. */
export const specialistName = (role) => `kiln-specialist-${role}`;

const scalar = (value) => JSON.stringify(String(value));

const bullets = (lines) => lines.map((line) => `- ${line}`).join("\n");

const fields = (record) =>
  Object.entries(record)
    .map(([key, description]) => `- \`${key}\` — ${description}`)
    .join("\n");

/**
 * The complete text of one role definition.
 *
 * @param {"research"|"planning"|"validation"} role
 * @returns {string}
 */
export function renderRole(role, { contract: injected } = {}) {
  const prose = ROLE_PROSE[role];
  if (!prose) throw new RoleRenderRefusal(RENDER_REFUSAL.PROSE_MISSING, `No authored prose for role ${JSON.stringify(role)}.`);

  // ⚠️ THE AUTHORED SET IS CLOSED TOO. A field added here rather than to the contract is a tool list, a
  // boundary or a forbidden action being restated by hand, which is the drift this design exists to
  // make impossible.
  const unexpected = Object.keys(prose).filter((key) => !AUTHORED_FIELDS.includes(key));
  if (unexpected.length)
    throw new RoleRenderRefusal(
      RENDER_REFUSAL.PROSE_UNEXPECTED_FIELD,
      `Role ${role} authors ${unexpected.join(", ")}, which the contract owns. Authored fields are ${AUTHORED_FIELDS.join(", ")}.`
    );
  for (const field of AUTHORED_FIELDS) {
    const value = prose[field];
    const empty = value === undefined || value === null || (typeof value === "string" && value.trim() === "") || (Array.isArray(value) && value.length === 0) || (typeof value === "object" && !Array.isArray(value) && Object.keys(value).length === 0);
    if (empty) throw new RoleRenderRefusal(RENDER_REFUSAL.PROSE_EMPTY, `Role ${role} leaves ${field} empty.`);
  }

  // ⚠️ THE SEAM IS FOR THE GUARDS BELOW, NOT FOR CALLERS. Every real caller renders from the real
  // contract; a test injects one whose boundary derives nothing, because the three shipped roles all
  // derive tools and the no-tools refusal would otherwise be unreachable and untested.
  const contract = injected ?? contractFor(role);
  if (contract.unimplemented.length || contract.unknownMutations.length || contract.undefinedCapabilities.length)
    throw new RoleRenderRefusal(
      RENDER_REFUSAL.CONTRACT_UNSOUND,
      `Role ${role}'s contract reports unimplemented=${JSON.stringify(contract.unimplemented)}, ` +
        `unknownMutations=${JSON.stringify(contract.unknownMutations)}, ` +
        `undefinedCapabilities=${JSON.stringify(contract.undefinedCapabilities)}. A definition written over an ` +
        `unsound contract promises a tool nothing registers.`
    );

  // ⚠️ ACC-0072's SECOND SENTENCE, AT GENERATION TIME. A role with no tools must not produce a file at
  // all: the measured hazard is that an absent `tools:` line hands a child read, bash, edit and write
  // rather than narrowing it.
  if (contract.tools.length === 0)
    throw new RoleRenderRefusal(RENDER_REFUSAL.NO_TOOLS, `Role ${role} derives no tools. A definition with no tool list would inherit the agent's defaults.`);

  const body = SECTIONS.map(({ heading, field }) => {
    if (field === null) return `## ${heading}\n\n${bullets(contract.forbidden)}`;
    if (field === "outputSchema") return `## ${heading}\n\nReturn one JSON object with exactly these fields.\n\n${fields(prose.outputSchema)}`;
    return `## ${heading}\n\n${bullets(prose[field])}`;
  }).join("\n\n");

  return [
    "---",
    GENERATED_NOTICE,
    `name: ${scalar(specialistName(role))}`,
    `role: ${scalar(role)}`,
    `description: ${scalar(prose.description)}`,
    "tools:",
    ...contract.tools.map((tool) => `  - ${scalar(tool)}`),
    "---",
    "",
    `# ${prose.title}`,
    "",
    prose.description,
    "",
    body,
    "",
  ].join("\n");
}

/** Every role definition, keyed by the path it belongs at, relative to the tool root. */
export function renderRoles(roles) {
  const out = new Map();
  for (const role of roles) out.set(`${SPECIALISTS_DIR}/${role}.md`, renderRole(role));
  return out;
}
